# Generated by Django 5.0.7 on 2024-07-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
